### ISSUE TITLE
Render bug on Intel graphics

### ISSUE THREAD

**Issue by ori-sky** [shockkolate/polar4#12]
The latest changes which add the `Eval` function to the fragment shader seem to cause screen rendering to break and only render one color, as far as I can tell. Currently we can only reproduce this on an integrated Intel graphics card on Mark's system.

**Comment by darkf** [comment]
worked fine for me

**Comment by ori-sky** [comment]
This bug is potentially fixed now. I don't know the reason for the bug but I've reverted the code structure to before I added a separate Eval function. We'll need to wait until Monday to see if this was successful.

**Comment by ori-sky** [comment]
This bug appears to be caused by either of two changes, and both changes must be reverted in order for the bug to disappear.

* `numSamples` is set to a constant value
* The loop break condition is changed from `>` to `>=`
