### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by ori-sky** [shockkolate/polar4#14]
We need a website for the game, probably built on either Bootstrap or Foundation. Aside from this being a requirement for Steam games, it's also a really good idea in general.

**Comment by darkf** [comment]
no bootstrap

**Comment by ori-sky** [comment]
The base website design is complete. We still need to add the Steam widget but we can't do this until the game is on the store.

**Comment by ori-sky** [comment]
The Steam widget has now been added and aligned correctly. This concludes this issue as the early access website is now complete.
